language: java
jdk:
- openjdk10
before_install:
- chmod +x gradlew
- chmod +x gradle/wrapper/gradle-wrapper.jar
script:
- ./gradlew test build
deploy:
  provider: script
  script: ./gradlew uploadArchives
  on:
    condition: $TRAVIS_BRANCH =~ ^master|production$

